# Example of a config file that I want cgx to be able to parse and use
# A system-wide config file will be read if present, from `/etc/cgx.toml` on Linux and macOS (and on Windows the
# idiomatic equivalent)
# User-specific config files will be read if present, from `$XDG_CONFIG_HOME/cgx/cgx.toml` or the platform equivalent
# This file can be at the root of a project, or in a subdirectory, or in a parent directory.
#
# Config settings are additive.  Settings from the system config file are overwridden by the user config file, which are
# overwritten by the settings in each directory up to the root.
#
# So if I have a project in `~/projects/work/project1`, and in that directory I run a `cgx` command, it will look for
# and read the following config files, in order, with later files overriding earlier ones if they both contain the same
# setting:
# - `/etc/cgx.toml
# - `$XDG_CONFIG_HOME/cgx/cgx.toml`
# - `/cgx.toml`
# - `/home/cgx.toml`
# - `~/cgx.toml`
# - `~/projects/cgx.toml`
# - `~/projects/work/project1/cgx.toml`

bin_dir               = "~/.local/bin"
build_dir             = "~/.local/build"
cache_dir             = "~/.cache/cgx"
locked                = true
log_level             = "info"
offline               = false
resolve_cache_timeout = "1h"
toolchain             = "stable"

# By default, `cgx` will use crates.io if no registry is explicitly specified.  This overrides that default
default_registry = "my-registry"

# List where cgx should look for pre-built binaries, before building from source.
# If this is set to an empty array, it disables using pre-built binaries entirely, and always builds from source.
# Particularly security-conscious users may prefer that.
binary_providers = [
  # The same logic used by `cargo-binstall`
  "binstall",

  # GitHub releases on the repo where the crate is located (if the crate's repo is on Github)
  "github-releases",

  # GitLab releases on the repo where the crate is located (if the crate's repo is on GitLab)
  "gitlab-releases",

  # The community-driven repository of pre-built binaries
  "quickinstall",
]

# `cgx` can invoke any binary crate on crates.io, it doesn't need to be listed here, but by listing
# a tool here it can be pinned to a specific version, or customized in some way by using a different registry,
# or a git repo, or a local path, or customizing features enabled.
#
# Each entry has the same format as a dependency in Cargo.toml
[tools]
# This is not a very useful entry, as it matches what is already the default behavior when `cgx` is invoked with
# a tool that doesn't have a specific version
ripgrep   = "*"
taplo-cli = { version = "1.11.0", features = ["schema"] }

# Not all crates have intituive names.  You can specify aliases here, to alias a more familiar name.
# Note that by doing this, actual crates with the aliased name become inaccessible
[aliases]
rg    = "ripgrep"
taplo = "taplo-cli"
